lock: retry Windows file creation on ERROR_SHARING_VIOLATION
I don't know what's different from PermissionDenied, but I got the following
error from Windows CI:

    thread '<unnamed>' panicked at lib\tests\test_git.rs:5546:61:
    called `Result::unwrap()` on an `Err` value: OpHeadsStore(Lock(FileLockError
    { message: "Failed to open lock file", path: "...\\op_heads\\heads\\lock",
    err: Os { code: 32, kind: Uncategorized, message: "The process cannot access
    the file because it is being used by another process." } }))